[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa7be7dd54e980195a2613914fa3584447351897"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "d6841ef79e38234a52133ac2c2e4d36500c55154a5aacf7fe584d9799c541f21"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.aarch64-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d791b26d0c991caf6bfdf9177452cc1c73313cd3"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "8859c8841416d3e09d0adff8f895d4d7c6755bd7727c29b168bd7c1836751bb5"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.aarch64-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8dc9576c364abd79a34b2d9a290ff5547708f11"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "5d2106e84a6ccfa76b53fe599dfc74f40676fc31a1e9f9e1b5181e135d85de42"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b716bde89b8036af327e2f5232672570892043e0"
os = "windows"

    [[FastJet.download]]
    sha256 = "420692bcedd9a2b08ab9472b610926142b58fb3f6d8e64084c462cb02f98bff4"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9815fbaa743d274a83edffb1899b20370321eca"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "aba25c3bd9daf174f78b697b380d35f10c36c89b61faf1cc11a636d0b0b55802"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.i686-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f80e1fb415761365f1c0d0b588bd3c8b14c0f7a"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "54343b25a6091b477906eb34949fcf18d6098cd7f75fcbe23d0245743794fbae"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c304fad95615fdb8c14887c3fd5ab03785d2f883"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "b3e05ff775941980974f51d98fa33c7f4da3afce5991daaceb186f9198a5cbb1"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8dba44576c22ec6b97eff9cff5967f5cd26f2f3"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "02c3c1fbc0ee8de5b0ba729d698ec61398b341b7189d86b4c1990b086942e8ae"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.i686-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7e91f5c9f647f763786e4f126a9f6e656ddf1b4"
os = "macos"

    [[FastJet.download]]
    sha256 = "ae8745787cfba03f76dbe53186d7f1070adaf713c073e3546660061b384bfb95"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4ec3e2cff8acc1204438c2ae0af1801fb6d4179"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "7ebd275532a914c87ddc9e739b728679061eb23051c975752f34610fa97c13b8"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.i686-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1dd0e72b953d69b645dc1339681287e9c1db724"
os = "windows"

    [[FastJet.download]]
    sha256 = "c2131fe138541449565ea17ff025eeb7d482b5015cd02da024eda1fade97e11f"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "687ba85eb3c1c7480538e4c3042d8e44c7a3a271"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "729d45eda1f035b6cc2f0549d381ba38fa561da95133a56448b396a2bceb4ecd"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "344713b2656ed7e0fcd326c901b4d0f8ba119638"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "0043000245a1ea9d3b438df6ecf342a206a2deb5f4b4c303742f09ea9cd87f82"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6c6286a573111596e5fd5e944bd669be53c4974"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "19fb4ea1ead77d56df11f6cad40104aba50e85332e77cfd7abd62b485181e2e6"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.aarch64-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "353d07821c047869bc6261a33c6bcdd20b7167fa"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "f5b5af8860e5adae3f1eeed643c291008eb66fe24c764ed6870ed96ba16ca8c6"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d287fefade9d4911ed0dffda48be1638fd80d894"
os = "macos"

    [[FastJet.download]]
    sha256 = "c7124daefce53dccfea896a9b0e59e24bef4f49a7e808ea98ab3131ef2bb0452"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ddfc0e245c53cdb461ec6fa5b54823698c40ac7"
os = "freebsd"

    [[FastJet.download]]
    sha256 = "2e3b8ca86eccb095dfde686049c18a78eb1c77ecc2dbce03377c3c839f970e77"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[FastJet]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18260dbd88ac5ee9f9dbe339b25d7711c3395a14"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "9f3c59528e492af44fef01918a96f36304b47f58b7ed2e25f2216300497f943d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb3b2ea7db3612d0e7304dd06a2af6c32b0d03bf"
os = "windows"

    [[FastJet.download]]
    sha256 = "666f9514ffb7a069d6cd40646338812ade17d20874032585e49e5d57a1cb1572"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.i686-w64-mingw32-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4929bef4403cf2309830c4db2f0e66764d9a89a2"
os = "windows"

    [[FastJet.download]]
    sha256 = "a5768a1c59773b63e0e4db081023715635bf161fb72587575b89d79009d2e365"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.i686-w64-mingw32-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff5ca6b7a4f1139254eaa82a83438d14fb49bdd0"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "9f38635812a4bbe8e975713c912e49e7a9850eafb6d6edd66d9393bbe9685fd1"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cde37c78c3b573e7c79f618429ae350bf5ed5fd"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "da4fd2fb1fa8c57b39eaf8221a5868b56ed938493c8b883e6461424a644a9e42"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dcff0390ac82642cf79d5a2cf9cc6de08323311"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "65c7cc58c0a215bc599cca389802cc8ee6aa34160cfcae1e95b029ccf3c7e3b3"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.aarch64-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a36cf65c1c34e56d4cfd20d7af7abdb3d39fcb5b"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "e015c619ffccc1fe1064bd30839cabafea2f42399960681bd9bf99e7d123c3b1"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5a30b9bb41cba0c2b5750d9856a7a6c44fbaf5e"
os = "freebsd"

    [[FastJet.download]]
    sha256 = "c3a5e63e3207c373b04d7829a871acb5cea219a382667e490aa50de045d9c3e3"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a45d69211443f1cbebd645345e19a4acdddeb66c"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "f2cd42813d94314647385dd8dd43ae28310f85f3f4916a73350eba93078ff89c"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+0/FastJet.v3.3.4.i686-linux-musl-cxx03.tar.gz"
