[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f5b4430a48e683c5eb95bc9a99d02cad46a4b5b"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "96f572bc596dcd64a2a0fd117ee2faa309f9292fafaeed1b38b6e6d6b003226c"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.aarch64-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0974617fd1cce634ffc2b7754aee78f003e387cd"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "878ac304ee90f9bf193bb0f1683d9299c9731af7b77fce4966ea72b4700af989"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.aarch64-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a263629befe9e4d54d86034ac310e9d419140d7f"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "674cf0854dcb042c8b9048b5f432d16ec32b0bb5a46f161667320234458a0c34"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3b0902aec9854e81116f49a7f0cec677b7a0c82"
os = "windows"

    [[FastJet.download]]
    sha256 = "e514738bd053717c051a2b9c70880ea16bcf2111c807bda2aeddab98c9f384a8"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfacb916e4210d4bdc75e76e249c55315bf95ef2"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "af938b19b98fb8e782735270b2f34b5a0e59815dc878a53640d8b2b2895f0677"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.i686-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13ed23c8fddca980dc01d611b8aba8fbb7b2f921"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "9d5c86612180b10f4ee7ae883450d0bd45436cb2a309dad84b0e285aed28636e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "072f3b03caa1a1a70e298ce98f0af6225df82909"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "372051543489ee815b891a925d58565a4df030e97215bd573de93d576a9cb990"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2971766af2ec0fb19ad514be5201f7c86cbf5ddc"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "642628768cd8a267d810e63b71e4621dddcc764f6eee6178ab94ae5470fa0d43"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.i686-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2a8ba54000032b8f20727439a3017561d6c1387"
os = "macos"

    [[FastJet.download]]
    sha256 = "71721ca7a1b062aed6d7f6efdcc4640676be27be0fbf9653e8350545ddddb734"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7c441bb603a5496d6428e0d77c92f113ca42b32"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "41606d25bbad35cb7522eb8fc3ba6a9f12649a4bc38dcfedb6f602ff968cde0c"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.i686-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f003c67cff21ed91bfc9e9691dd806c1e32b9e39"
os = "windows"

    [[FastJet.download]]
    sha256 = "11e003ba894a8891c36395ba799b56f2a9b2ba51b5c397812e7343366294f89b"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30b4c25f7e3cccd3a8c6d0a0ac93595878abd5a9"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "c9deee93fd47ca419fd050fe836b6e7db0687d75022278c0b9f57f321ed18c0b"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bde8cd68315875c15685c30031b583e1a747dd01"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "ae473a8d9e65d1a36ee246e43d5060fc0d52e7128e01653293db0ef77f6b8b54"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8861c5525e5eff9f3407511b8ebc4af7f7f9ea3"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "2682ebc98abb12d3d06d524dedfa937b693a882ef586e2cc8b677a2e59c00180"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.aarch64-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a38a9ba468e2a3c30f17e1733bb6a9497b0bc37e"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "9d4ce4aa0d638ccbd30bb2fd110a38a231bd3f3927af63f55a897586e245aa47"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97658bea07f69ca86dc2dacc32302085d58d5439"
os = "macos"

    [[FastJet.download]]
    sha256 = "d3c700f4e9e67cd358b2b9b3fea808a0831b45e13af4a253ac3eab4590b08054"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c6dbd442464f7b8121fc4d43497ed7c94d870cf"
os = "freebsd"

    [[FastJet.download]]
    sha256 = "bcc1e3e3eae55a9d2e6b7d159d88da350199a1a217817cbf854180b5a0c017eb"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[FastJet]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b80b5f3af4888297f215e04b6bec8eaee84f0ea"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "74cba73ea107eb041d321682bf7a664fdcf13d2c88da05ddeba1900a83a00fdb"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba6d4962228c9d118abec80f0b692b83b809ad52"
os = "windows"

    [[FastJet.download]]
    sha256 = "4e736e40a178db705a07f982b0e5eb4594db1d4c69eb00e16695c7be9585df37"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.i686-w64-mingw32-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86d4d9043858eeb5aa735047d10030040d85008a"
os = "windows"

    [[FastJet.download]]
    sha256 = "10085186b1a1828f9a510abead8a6b4ed4627672b69f2ca7ef0c0fe4ed3a8b4e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.i686-w64-mingw32-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bc7f46709d2c769d086e2ef56ed369a29f7837d"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "3b2072b70689b7c36e2116a9ec96e0f2bc2ea8ae0500f85caa3a05d0c5133c12"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "045f08c8a635ac556c0ee4666f9341a09dd4c335"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "6addcfa4d65d61223a8dae7cf651204595af0cf24c8d9acba89dfde49dcf637e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3ab83fd3721d0763b8afeb83c512566736be414"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "2a2a9137117439e571bf0cc606b61754e56fa5f7ee48f6a8ba2b106ea415e7f9"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.aarch64-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b0fe313ffaddf4e57bb4cbf01646bc5556f7fc"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "2dfcd89bc6cc9dc332605de6491f529ac945a491f13a8cc1c9e506444484bf61"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a600571b40ad3ed2e24006cc0ddacf898b8482a4"
os = "freebsd"

    [[FastJet.download]]
    sha256 = "48ae7746197a187e568238dd51a5dd49bd210a5fbcbb3e9c9484180099d5e0f8"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ebb932ea1c937802a0ddb558fa1521ffb1eda78"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "e1cc5201330f4bde18910e58815ff56b1399df8a1e49bb9b4215b8c666598630"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.3.4+1/FastJet.v3.3.4.i686-linux-musl-cxx03.tar.gz"
