[[FastJet]]
arch = "aarch64"
git-tree-sha1 = "caee49bcf32b8c2f779d4b0e8ecddda7032ed662"
os = "macos"

    [[FastJet.download]]
    sha256 = "046b3bce86e50f06378b3460e556a5aa8d4af05de1588bef2039c3a94b55e720"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.aarch64-apple-darwin.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "094569fb124577807e6f211005540eb920f89bb6"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "1415e7de3ecaf4a26534b047b9245aae326c8a1ce562699b55a667d971a85869"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99eab467ac4544a3e2565016706b27315521d86e"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "7519d99131a52431aabd7c77f216483a35111ff5622625482dca63f546295fb5"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2921bcdce5cb64b704fa812349400e3a41618fa"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "906977d92fb2ef13db1fb89c189a8bacb25362339d3568e6c43d46a0df173839"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df515ecef9fb6d641a5f57b75679e581b4bf66c9"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "5484684070cc22d0a5e0d1216a4f28f22ada28b5e2780b81776b5b83740fbb11"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "920fe927e21455685a61355acdc30a5db7c99156"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "e7dfbf9af55bab76e8a16ff61253476fab2d0217dc7ae966fd93853c39b6dcf0"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[FastJet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "104a8ca83b0e3b2f668a360e9632a7e8f3f04cf5"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "235d08e4271bd68bda46da498285872bb05c205fcc701b97afb9c2c458dd6067"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[FastJet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5bd375d4cb32b31355d87ba63bf3346d9ad81ef"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "3714e9d942eaa4f7d5fafc5ff997dedbff7644b5e4b53a694320c38c21155fd7"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[FastJet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "936596d6bbbc6824f5c3fd60a1a47860187b4838"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "900e3897ed47a7d283b714742537b8027a16372cb30f89a46a160f309aef704f"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4b415d9aa530eaf78ae6584707c144e393547a3"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "8fc5abdaae65718012d0dfd781b91616a1d11774a285929684d413b799e6659f"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[FastJet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "302ac2251e412d810080ede6a2e00ee8311f99c3"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "a46439525a4512b09738d6745194315234b8ebd42d2c9f12448c8eae4fbd88df"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FastJet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "727a53703eaab6e45c5656079fc461220a64225a"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "f174019dd86c0790dd4d33a2d1c2546473fc3121021f2b46af9e2a0036279b6f"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[FastJet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e124e424c8e35f81aa1ba95043fd98d9029e84e"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "f744cabcb2e40eabfaedf94ab6eac2e05c931da67cd787e3c46a1b3cd84b9f14"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7edb84be80bd2b01f88bd0bcd2653fa2a5d87f4"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "cf9dcaefa5929246f4969733a79052ff0790cfb01add50a0670493f7b009b57e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.i686-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2e9829026d1e4307ab05d7df2e469c739123e56"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "754908ed78e1ab972de6a76d14887c91f545926817ba2b8d04433e61ba301414"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.i686-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8b16a25b9f56f12cd8f2d8ea41ef6a6ca93778a"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "2f5bce0d749dde3f5ee342170085e7c3d51a6753e825ee897693d35ab788d13f"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.i686-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af6c1fa951a7c71edb85949d1de71f0d40120435"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "85f8b093ba57d29ef8d2f5695993e8b42348d3493838cf2c43a25baf123048c8"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.i686-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3048a2c3bf9422d1f8ab3456e34d637030cff835"
os = "windows"

    [[FastJet.download]]
    sha256 = "9ed5069029be915fcaccb20483541da458939663d0c93c698cf81a35c4fb30a8"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[FastJet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1211ae35ad68f12e081ece696596ff4814c1b9b"
os = "windows"

    [[FastJet.download]]
    sha256 = "097dc24033a24e3a43045ed07c5c0bcb3e42a58aa200d48a6483a8c30edfc21f"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[FastJet]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b49b221220812615a9c4950c99209e4d66cba383"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "86f9240144726cc9988439afb53056ecc9991e832cc5e21d58b5b58acf45b7ac"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "564928cc6ed8f97e0dbfcc8608264de1060e5ff9"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "47b5fda71aa68e0d20358cac5534f3eb86f33abd43141ec899259ffd71685122"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
git-tree-sha1 = "8a4dd50c6393b8be474afb478ab3c7d9cc3c0fb4"
os = "macos"

    [[FastJet.download]]
    sha256 = "ddef493b71a26cde49e29932895571447275df3c50deac20bc8d0deb4f1d69f4"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-apple-darwin.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e25c40f2b14d069420c1e6eff675363813319546"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "502ecac0be573bf591515d83a5fd7465778af4838e3ea4eeb8bdb9b3f105ad45"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7159f593b4ec8bf5055ced14c4c993f37b64997d"
libc = "glibc"
os = "linux"

    [[FastJet.download]]
    sha256 = "182a5f391ab0d4e45f4787bd7f91eaab6eb2ba463ae2ecec50c474fcd0a7e3fc"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c35a6b11c939eba634165f2e6e6e098b45bd0dc"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "2602768712c6f0a8cd1caed527f14fb6491bc40293fd847fb31e08e9afb09686"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "014ac4aa8b253288f0842b4abf1c38835efa0b29"
libc = "musl"
os = "linux"

    [[FastJet.download]]
    sha256 = "e6e2498b4d8f30f3775ab4a4a92c2d7812ba5e37155e1dd7743b589cd3e3d29d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[FastJet]]
arch = "x86_64"
git-tree-sha1 = "a928d572f8c0eb236431a608c8eadac3e0bcb166"
os = "freebsd"

    [[FastJet.download]]
    sha256 = "bc98c7ce417bca0098b21b3798a2757f10fac9d24d29e1fd4ce1667719d5a42d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-unknown-freebsd.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bf6898c2cee5a28fe7946a803de5e919b750e0e"
os = "windows"

    [[FastJet.download]]
    sha256 = "e4f53444741308151b202b7f6b9f87a31bcf76a73d92f8f0540dbd2396b13333"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[FastJet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62e9819fc2ab4e12d0062a9cfbcb3346f1d19506"
os = "windows"

    [[FastJet.download]]
    sha256 = "6affd2db18465533c4c2d4a79455cebbb505c6b7c9e873fbf766fc16789f888e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_jll.jl/releases/download/FastJet-v3.4.0+0/FastJet.v3.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
