# Autogenerated wrapper script for FastJet_jll for aarch64-apple-darwin
export libClusteringVetoPlugin, libConstituentSubtractor, libEnergyCorrelator, libFlavorCone, libGenericSubtractor, libJetCleanser, libJetFFMoments, libJetsWithoutJets, libLundPlane, libNsubjettiness, libQCDAwarePlugin, libRecursiveTools, libScJet, libSoftKiller, libSubjetCounting, libValenciaPlugin, libVariableR, libfastjet, libfastjetplugins, libfastjettools, libsiscone, libsiscone_spherical

JLLWrappers.@generate_wrapper_header("FastJet")
JLLWrappers.@declare_library_product(libClusteringVetoPlugin, "@rpath/libClusteringVetoPlugin.dylib")
JLLWrappers.@declare_library_product(libConstituentSubtractor, "@rpath/libConstituentSubtractor.dylib")
JLLWrappers.@declare_library_product(libEnergyCorrelator, "@rpath/libEnergyCorrelator.dylib")
JLLWrappers.@declare_library_product(libFlavorCone, "@rpath/libFlavorCone.dylib")
JLLWrappers.@declare_library_product(libGenericSubtractor, "@rpath/libGenericSubtractor.dylib")
JLLWrappers.@declare_library_product(libJetCleanser, "@rpath/libJetCleanser.dylib")
JLLWrappers.@declare_library_product(libJetFFMoments, "@rpath/libJetFFMoments.dylib")
JLLWrappers.@declare_library_product(libJetsWithoutJets, "@rpath/libJetsWithoutJets.dylib")
JLLWrappers.@declare_library_product(libLundPlane, "@rpath/libLundPlane.dylib")
JLLWrappers.@declare_library_product(libNsubjettiness, "@rpath/libNsubjettiness.dylib")
JLLWrappers.@declare_library_product(libQCDAwarePlugin, "@rpath/libQCDAwarePlugin.dylib")
JLLWrappers.@declare_library_product(libRecursiveTools, "@rpath/libRecursiveTools.dylib")
JLLWrappers.@declare_library_product(libScJet, "@rpath/libScJet.dylib")
JLLWrappers.@declare_library_product(libSoftKiller, "@rpath/libSoftKiller.dylib")
JLLWrappers.@declare_library_product(libSubjetCounting, "@rpath/libSubjetCounting.dylib")
JLLWrappers.@declare_library_product(libValenciaPlugin, "@rpath/libValenciaPlugin.dylib")
JLLWrappers.@declare_library_product(libVariableR, "@rpath/libVariableR.dylib")
JLLWrappers.@declare_library_product(libfastjet, "@rpath/libfastjet.0.dylib")
JLLWrappers.@declare_library_product(libfastjetplugins, "@rpath/libfastjetplugins.0.dylib")
JLLWrappers.@declare_library_product(libfastjettools, "@rpath/libfastjettools.0.dylib")
JLLWrappers.@declare_library_product(libsiscone, "@rpath/libsiscone.0.dylib")
JLLWrappers.@declare_library_product(libsiscone_spherical, "@rpath/libsiscone_spherical.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libClusteringVetoPlugin,
        "lib/libClusteringVetoPlugin.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libConstituentSubtractor,
        "lib/libConstituentSubtractor.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libEnergyCorrelator,
        "lib/libEnergyCorrelator.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libFlavorCone,
        "lib/libFlavorCone.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGenericSubtractor,
        "lib/libGenericSubtractor.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetCleanser,
        "lib/libJetCleanser.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetFFMoments,
        "lib/libJetFFMoments.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetsWithoutJets,
        "lib/libJetsWithoutJets.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libLundPlane,
        "lib/libLundPlane.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libNsubjettiness,
        "lib/libNsubjettiness.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libQCDAwarePlugin,
        "lib/libQCDAwarePlugin.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRecursiveTools,
        "lib/libRecursiveTools.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libScJet,
        "lib/libScJet.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSoftKiller,
        "lib/libSoftKiller.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSubjetCounting,
        "lib/libSubjetCounting.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libValenciaPlugin,
        "lib/libValenciaPlugin.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libVariableR,
        "lib/libVariableR.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjet,
        "lib/libfastjet.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjetplugins,
        "lib/libfastjetplugins.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjettools,
        "lib/libfastjettools.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsiscone,
        "lib/libsiscone.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsiscone_spherical,
        "lib/libsiscone_spherical.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
