# Autogenerated wrapper script for FastJet_jll for i686-w64-mingw32-cxx03
export libClusteringVetoPlugin, libConstituentSubtractor, libEnergyCorrelator, libFlavorCone, libGenericSubtractor, libJetCleanser, libJetFFMoments, libJetsWithoutJets, libLundPlane, libNsubjettiness, libQCDAwarePlugin, libRecursiveTools, libScJet, libSoftKiller, libSubjetCounting, libValenciaPlugin, libVariableR, libfastjet, libfastjetplugins, libfastjettools, libsiscone, libsiscone_spherical

JLLWrappers.@generate_wrapper_header("FastJet")
JLLWrappers.@declare_library_product(libClusteringVetoPlugin, "libClusteringVetoPlugin.dll")
JLLWrappers.@declare_library_product(libConstituentSubtractor, "libConstituentSubtractor.dll")
JLLWrappers.@declare_library_product(libEnergyCorrelator, "libEnergyCorrelator.dll")
JLLWrappers.@declare_library_product(libFlavorCone, "libFlavorCone.dll")
JLLWrappers.@declare_library_product(libGenericSubtractor, "libGenericSubtractor.dll")
JLLWrappers.@declare_library_product(libJetCleanser, "libJetCleanser.dll")
JLLWrappers.@declare_library_product(libJetFFMoments, "libJetFFMoments.dll")
JLLWrappers.@declare_library_product(libJetsWithoutJets, "libJetsWithoutJets.dll")
JLLWrappers.@declare_library_product(libLundPlane, "libLundPlane.dll")
JLLWrappers.@declare_library_product(libNsubjettiness, "libNsubjettiness.dll")
JLLWrappers.@declare_library_product(libQCDAwarePlugin, "libQCDAwarePlugin.dll")
JLLWrappers.@declare_library_product(libRecursiveTools, "libRecursiveTools.dll")
JLLWrappers.@declare_library_product(libScJet, "libScJet.dll")
JLLWrappers.@declare_library_product(libSoftKiller, "libSoftKiller.dll")
JLLWrappers.@declare_library_product(libSubjetCounting, "libSubjetCounting.dll")
JLLWrappers.@declare_library_product(libValenciaPlugin, "libValenciaPlugin.dll")
JLLWrappers.@declare_library_product(libVariableR, "libVariableR.dll")
JLLWrappers.@declare_library_product(libfastjet, "libfastjet-0.dll")
JLLWrappers.@declare_library_product(libfastjetplugins, "libfastjetplugins-0.dll")
JLLWrappers.@declare_library_product(libfastjettools, "libfastjettools-0.dll")
JLLWrappers.@declare_library_product(libsiscone, "libsiscone-0.dll")
JLLWrappers.@declare_library_product(libsiscone_spherical, "libsiscone_spherical-0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libClusteringVetoPlugin,
        "bin\\libClusteringVetoPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libConstituentSubtractor,
        "bin\\libConstituentSubtractor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libEnergyCorrelator,
        "bin\\libEnergyCorrelator.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libFlavorCone,
        "bin\\libFlavorCone.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGenericSubtractor,
        "bin\\libGenericSubtractor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetCleanser,
        "bin\\libJetCleanser.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetFFMoments,
        "bin\\libJetFFMoments.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetsWithoutJets,
        "bin\\libJetsWithoutJets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libLundPlane,
        "bin\\libLundPlane.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libNsubjettiness,
        "bin\\libNsubjettiness.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libQCDAwarePlugin,
        "bin\\libQCDAwarePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRecursiveTools,
        "bin\\libRecursiveTools.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libScJet,
        "bin\\libScJet.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSoftKiller,
        "bin\\libSoftKiller.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSubjetCounting,
        "bin\\libSubjetCounting.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libValenciaPlugin,
        "bin\\libValenciaPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libVariableR,
        "bin\\libVariableR.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjet,
        "bin\\libfastjet-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjetplugins,
        "bin\\libfastjetplugins-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjettools,
        "bin\\libfastjettools-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsiscone,
        "bin\\libsiscone-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsiscone_spherical,
        "bin\\libsiscone_spherical-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
