# Autogenerated wrapper script for FastJet_jll for x86_64-linux-gnu-cxx03
export libClusteringVetoPlugin, libConstituentSubtractor, libEnergyCorrelator, libFlavorCone, libGenericSubtractor, libJetCleanser, libJetFFMoments, libJetsWithoutJets, libLundPlane, libNsubjettiness, libQCDAwarePlugin, libRecursiveTools, libScJet, libSoftKiller, libSubjetCounting, libValenciaPlugin, libVariableR, libfastjet, libfastjetplugins, libfastjettools, libsiscone, libsiscone_spherical

JLLWrappers.@generate_wrapper_header("FastJet")
JLLWrappers.@declare_library_product(libClusteringVetoPlugin, "libClusteringVetoPlugin.so")
JLLWrappers.@declare_library_product(libConstituentSubtractor, "libConstituentSubtractor.so")
JLLWrappers.@declare_library_product(libEnergyCorrelator, "libEnergyCorrelator.so")
JLLWrappers.@declare_library_product(libFlavorCone, "libFlavorCone.so")
JLLWrappers.@declare_library_product(libGenericSubtractor, "libGenericSubtractor.so")
JLLWrappers.@declare_library_product(libJetCleanser, "libJetCleanser.so")
JLLWrappers.@declare_library_product(libJetFFMoments, "libJetFFMoments.so")
JLLWrappers.@declare_library_product(libJetsWithoutJets, "libJetsWithoutJets.so")
JLLWrappers.@declare_library_product(libLundPlane, "libLundPlane.so")
JLLWrappers.@declare_library_product(libNsubjettiness, "libNsubjettiness.so")
JLLWrappers.@declare_library_product(libQCDAwarePlugin, "libQCDAwarePlugin.so")
JLLWrappers.@declare_library_product(libRecursiveTools, "libRecursiveTools.so")
JLLWrappers.@declare_library_product(libScJet, "libScJet.so")
JLLWrappers.@declare_library_product(libSoftKiller, "libSoftKiller.so")
JLLWrappers.@declare_library_product(libSubjetCounting, "libSubjetCounting.so")
JLLWrappers.@declare_library_product(libValenciaPlugin, "libValenciaPlugin.so")
JLLWrappers.@declare_library_product(libVariableR, "libVariableR.so")
JLLWrappers.@declare_library_product(libfastjet, "libfastjet.so.0")
JLLWrappers.@declare_library_product(libfastjetplugins, "libfastjetplugins.so.0")
JLLWrappers.@declare_library_product(libfastjettools, "libfastjettools.so.0")
JLLWrappers.@declare_library_product(libsiscone, "libsiscone.so.0")
JLLWrappers.@declare_library_product(libsiscone_spherical, "libsiscone_spherical.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libClusteringVetoPlugin,
        "lib/libClusteringVetoPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libConstituentSubtractor,
        "lib/libConstituentSubtractor.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libEnergyCorrelator,
        "lib/libEnergyCorrelator.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libFlavorCone,
        "lib/libFlavorCone.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGenericSubtractor,
        "lib/libGenericSubtractor.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetCleanser,
        "lib/libJetCleanser.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetFFMoments,
        "lib/libJetFFMoments.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libJetsWithoutJets,
        "lib/libJetsWithoutJets.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libLundPlane,
        "lib/libLundPlane.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libNsubjettiness,
        "lib/libNsubjettiness.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libQCDAwarePlugin,
        "lib/libQCDAwarePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libRecursiveTools,
        "lib/libRecursiveTools.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libScJet,
        "lib/libScJet.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSoftKiller,
        "lib/libSoftKiller.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSubjetCounting,
        "lib/libSubjetCounting.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libValenciaPlugin,
        "lib/libValenciaPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libVariableR,
        "lib/libVariableR.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjet,
        "lib/libfastjet.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjetplugins,
        "lib/libfastjetplugins.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfastjettools,
        "lib/libfastjettools.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsiscone,
        "lib/libsiscone.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsiscone_spherical,
        "lib/libsiscone_spherical.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
